Add complex recursion AST check functionality
ls1intum/Ares pull request #370
Opened 2024-05-03 16:17 UTC by sarpsahinalp

2024-05-13 09:07 UTC, Strohgelaender reviewed
Your PR contains many error messages annotated with "$NON-NLS-1$". I'm not sure about the localization state of the javaparser parts in Ares, but I think these user-facing error messages should also offer translations.

2024-05-13 09:07 UTC, Strohgelaender commented on pom.xml
> +			<version>3.25.9</version>
Please use a property to enusre that both javaparser dependencies use the same version.

2024-05-17 11:08 UTC, MaisiKoleni reviewed
Doing call graphs correctly is really difficult and close to impossible. I think the design and strictness should depend if the intended purpose. The default intended purpose of Ares functionality is grading (not just calculating a number for practice exercises in Artemis, but final exam grades in the curriculum), which is why security is so often important.
This security does not need to be absolute, incredibly difficult to circumvent is enough. 

For my taste, this is currently too easy. I will have a closer look at the code, but my time is limited, probably someone else from ls1intum needs to do that. My thoughts:
- what about method reference expressions? 
- what about virtual method invocation? (interfaces, superclasses) 

The last one is particularly hard. I had a similar problem not too long ago and had only partial success. Tools (SAST) that do this well are sold for good money, there is not much else.

In the end, you need to know what you want. I just want to warn you that it is either easy to circumvent or very difficult to implement. So again, think about your use case and what you need. If you are willing to make compromises, because the feature is intended for practice exercises / low stake assessment only, you can do so but should clearly document that scope.

2024-05-17 11:27 UTC, MaisiKoleni commented on src/test/java/de/tum/in/test/integration/testuser/subject/structural/astTestFiles/recursions/benchmarkASTRecursion/generate_classes.sh
> +#!/bin/bash
Those two are not needed right? At least I could not see what for.

2024-05-23 20:28 UTC, sarpsahinalp commented
> Your PR contains many error messages annotated with "$NON-NLS-1$". I'm not sure about the localization state of the javaparser parts in Ares, but I think these user-facing error messages should also offer translations.

The overall feedback will be improved via my thesis, therefore this PR was a quick solution for the AST Recursion check.

2024-05-23 20:33 UTC, sarpsahinalp commented
> Doing call graphs correctly is really difficult and close to impossible. I think the design and strictness should depend if the intended purpose. The default intended purpose of Ares functionality is grading (not just calculating a number for practice exercises in Artemis, but final exam grades in the curriculum), which is why security is so often important. This security does not need to be absolute, incredibly difficult to circumvent is enough.
> 
> For my taste, this is currently too easy. I will have a closer look at the code, but my time is limited, probably someone else from ls1intum needs to do that. My thoughts:
> 
> * what about method reference expressions?
> * what about virtual method invocation? (interfaces, superclasses)
> 
> The last one is particularly hard. I had a similar problem not too long ago and had only partial success. Tools (SAST) that do this well are sold for good money, there is not much else.
> 
> In the end, you need to know what you want. I just want to warn you that it is either easy to circumvent or very difficult to implement. So again, think about your use case and what you need. If you are willing to make compromises, because the feature is intended for practice exercises / low stake assessment only, you can do so but should clearly document that scope.

Via Java Symbol Resolver, we can handle most cases of interfaces, superclasses, and most expressions. However, as you mentioned, this functionality is currently intended for the introductory programming course, so with the exception of anonymous classes, most cases are covered.

2024-05-23 20:34 UTC, sarpsahinalp commented
> > Doing call graphs correctly is really difficult and close to impossible. I think the design and strictness should depend if the intended purpose. The default intended purpose of Ares functionality is grading (not just calculating a number for practice exercises in Artemis, but final exam grades in the curriculum), which is why security is so often important. This security does not need to be absolute, incredibly difficult to circumvent is enough.
> > For my taste, this is currently too easy. I will have a closer look at the code, but my time is limited, probably someone else from ls1intum needs to do that. My thoughts:
> > 
> > * what about method reference expressions?
> > * what about virtual method invocation? (interfaces, superclasses)
> > 
> > The last one is particularly hard. I had a similar problem not too long ago and had only partial success. Tools (SAST) that do this well are sold for good money, there is not much else.
> > In the end, you need to know what you want. I just want to warn you that it is either easy to circumvent or very difficult to implement. So again, think about your use case and what you need. If you are willing to make compromises, because the feature is intended for practice exercises / low stake assessment only, you can do so but should clearly document that scope.
> 
> Via Java Symbol Resolver, we can handle most cases of interfaces, superclasses, and most expressions. However, as you mentioned, this functionality is currently intended for the introductory programming course, so with the exception of anonymous classes, most cases are covered. I will improve the documentation further!

2025-02-19 15:24 UTC, xHadie requested changes
Overall, nice work. I just added a few nitpicky comments and requested clarification on some unclear parts.

2025-02-19 15:24 UTC, xHadie commented on src/test/java/de/tum/in/test/integration/testuser/subject/structural/astTestFiles/recursions/lambda/Example.java
> +public class Example {
Please add docs to this class to make its purpose clearer.

2025-03-22 22:46 UTC, closed without merging